### PR TITLE
Drag and drop support within the same list

### LINKED ISSUE #34: Cards drag and drop inside the same list

### PR DESCRIPTION
**Pull request by asdine**
Fixes #34

### CODE REVIEW

**Comment by jrmneveu** [comment]
Works fine for me, except for the list that exists before the feature.
In this case I can drag the card, but I can't drop it, the other cards are not moving.

sans titre

**Comment by asdine** [comment]
Should be better now with cards that don't have positions

**Comment by asdine** [comment]
@jrmneveu should we disable the hover effect on cards when dragging a card?
There are some cases when the card thinks it is still hovered even if it's not (it's hard to take a screenshot of that behaviour). If so, we might need to create a separate CSS class that manages the hover effect

**Comment by jrmneveu** [comment]
@asdine Yes, I see the problem and I agree with you. We should disable the hover effect. What is the best solution for you ? Add a new css class that takes in count this event for all cards on this list ?

**Comment by asdine** [comment]
I think we should have a separate simple CSS class that manages the hover effect. Something like:

```css
.blabla:hover {
  // the hover effect
}
```

By default, all cards would have this class, but if the user is dragging we would remove it on all cards.

What do you think?

**Comment by jrmneveu** [comment]
I agree, it is a very simple solution. Can we go with something like `.card-hover` ? If it is Ok for you, do it with this name and I will do my part after.

**Pull request merged**
